In [1]:
import numpy as np

In [12]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])

vec1 + vec2

array([14. , 10. , 10.6, 15.5])

In [4]:
list1 = [2, 4, 7, 2.5]
list2 = [12, 6, 3.6, 13]

list1+list2

[2, 4, 7, 2.5, 12, 6, 3.6, 13]

In [8]:
print(list(zip(list1, list2)))
[x + y for x, y in zip(list1, list2)]

[(2, 12), (4, 6), (7, 3.6), (2.5, 13)]


[14, 10, 10.6, 15.5]

In [13]:
vec1*vec2
# вектора должны быть одинаковой длины

array([24. , 24. , 25.2, 32.5])

In [16]:
vec1 = np.array([1, 2, 3])
vec2 = np.array([5, 6, 7, 8])

# длина неодинаково, поэтому возникает ошибка
# vec1+vec2
# vec1*vec2

In [20]:
vec1 = np.array([1, 2, 3, 10])
vec2 = np.array([5, 6, 7, 8])

print(vec1 > vec2)
print(vec1 >= 3)

[False False False  True]
[False False  True  True]


In [23]:
vec1 = np.arange(6)
print(vec1) #массив выводится без запятых
vec1

[0 1 2 3 4 5]


array([0, 1, 2, 3, 4, 5])

In [25]:
# Длина вектора

vec = np.array([3, 4])

length = np.sqrt(np.sum(vec**2))
print(length)

print(np.linalg.norm(vec))

5.0
5.0


In [29]:
# Расстояние между векторами

vec1 = np.arange(6, step=2)
print(vec1)

vec2 = np.random.randint(1,21, size=3)
print(vec2)

distance = np.sqrt(np.sum((vec1 - vec2)**2))
print(distance)

distance = np.linalg.norm(vec1-vec2)
print(distance)

[0 2 4]
[20  6 15]
23.173260452512935
23.173260452512935


Скалярное произведение 

In [33]:
vec1 = np.arange(2, 7)
vec2 = np.linspace(10, 20, 5)
print(vec1, vec2, sep='\n')

scalar_product = np.sum(vec1*vec2)
print(scalar_product)

[2 3 4 5 6]
[10.  12.5 15.  17.5 20. ]
325.0


In [34]:
# Скалярное произведение

scalar_product = np.dot(vec1, vec2)
print(scalar_product)

325.0


In [37]:
a = np.array([23, 34, 27])
b = np.array([-54, 1,  46])
c = np.array([46, 68, 54])

# сумма длин сонаправленных векторов должна быть равной 
# длине суммы двух векторов

In [39]:
# Длины векторов

alength = np.linalg.norm(a)
print(alength)

blength = np.linalg.norm(b)
print(blength)

clength = np.linalg.norm(c)
print(clength)

49.13247398615299
70.94363960215179
98.26494797230598


In [40]:
# а и б сонаправлены?

print(alength+blength == np.linalg.norm(a+b))

False


In [41]:
# а и c сонаправлены?

print(alength+clength == np.linalg.norm(a+c))

True


In [42]:
# b и c сонаправлены?

print(blength+clength == np.linalg.norm(b+c))

False


In [45]:
# Найдите пару векторов, расстояние между которыми больше 100.

# a, b
print(np.linalg.norm(a-b))

# a, c
print(np.linalg.norm(a-c))

# b, c
print(np.linalg.norm(b-c))


85.901105930017
49.13247398615299
120.6358155772986


In [48]:
# Найдите пару перпендикулярных векторов с помощью скалярного произведения (оно должно быть равно нулю)
print(np.dot(a, b))

print(np.dot(a, c))

print(np.dot(c, b))

34
4828
68


In [49]:
# Минимальное и максимальное значение в векторе

vec = np.array([2, 7, 18, 28, 5, 6])

print(vec.min())

print(vec.max())

2
28


In [50]:
# Среднее значение для вектора

print(vec.mean())

11.0


In [52]:
# Функция median() вычисляет медиану элементов массива.
# numpy.median(a, axis=None, out=None, overwrite_input=False, keepdims=False)

print(a)
np.median(a)

[23 34 27]


27.0

In [59]:
# Функция std() вычисляет среднеквадратичное (стандартное) отклонение значений элементов массива.
# numpy.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>)
# standart deviation

print(a)
print(round(np.std(a),2))
print(np.sum(a)/len(a))
print(np.linalg.norm(28-a)/np.sqrt((len(a))))

[23 34 27]
4.55
28.0
4.546060565661953
