- Элемент по любому номеру из массива можно получить за одно и то же время. 

- Обычно такое быстродействие массивов достигается за счёт того, что все элементы в массиве приведены к одному и тому же типу данных. 

- Обладают заданной программистом длиной.

- Объём выделенной памяти заданы заранее.

Параметры:
- размерность массива;
- длина массива;
- количество памяти, выделяемое на элемент;
- форма массива - размерность и длина по каждой оси;



In [1]:
import numpy as np

In [2]:
arr = np.array([1, 5, 2, 9, 10])
print(arr)
print(type(arr)) # n-dimensional array

print(arr.dtype)

[ 1  5  2  9 10]
<class 'numpy.ndarray'>
int32


In [3]:
arr_sq = np.array([
    [12, 45, 78],
    [34, 56, 13],
    [12, 98, 76]
])
arr_sq
print(arr_sq)

print(arr_sq.dtype)

[[12 45 78]
 [34 56 13]
 [12 98 76]]
int32


In [4]:
arr_sq = np.int8(arr_sq)
print(arr_sq.dtype)

int8


In [5]:
arr = np.int8(arr)

print(arr)
print(arr.dtype)

arr[2] = -260
print(arr)

arr[2] = '10' # преобразуется в число
print(arr)

# arr[2] = 'test' # ValueError


[ 1  5  2  9 10]
int8
[ 1  5 -4  9 10]
[ 1  5 10  9 10]


In [6]:
arr = np.array([12321, -1234, 3435, -214, 100], dtype=np.int8)
print(arr)

[ 33  46 107  42 100]


СВОЙСТВА NUMPY-МАССИВОВ

In [7]:
# размерность
print(arr.ndim)
print(arr_sq.ndim)

1
2


In [8]:
# число элементов в массиве
print(arr.size)
print(arr_sq.size)

5
9


In [9]:
# форма или структура массива
print(arr.shape)
print(arr_sq.shape)
print(arr_sq)

(5,)
(3, 3)
[[12 45 78]
 [34 56 13]
 [12 98 76]]


In [10]:
# сколько весит каждый элемент
print(arr.itemsize)
print(arr_sq.itemsize)

1
1


ЗАПОЛНЕНИЕ НОВЫХ МАССИВОВ

**arr = np.zeros(num)**

**arr = np.arange([start,] stop, [step,], dtype=None)**

**np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)**

In [11]:
zeros_arr = np.zeros(5, dtype=np.int8)
print(zeros_arr)

[0 0 0 0 0]


In [12]:
tr_zero_arr = np.zeros((5,4,3), dtype=np.float16)
print(tr_zero_arr)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [13]:
arr = np.arange(1, 6, 1, dtype=np.int8)
print(arr)

[1 2 3 4 5]


In [14]:
print(np.arange(2.5, 7, 0.5, dtype=np.float16))

[2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5]


In [15]:
arr, step = np.linspace(-6, 21, 60, retstep=True)
print(round(step, 2))
print(arr)

0.46
[-6.         -5.54237288 -5.08474576 -4.62711864 -4.16949153 -3.71186441
 -3.25423729 -2.79661017 -2.33898305 -1.88135593 -1.42372881 -0.96610169
 -0.50847458 -0.05084746  0.40677966  0.86440678  1.3220339   1.77966102
  2.23728814  2.69491525  3.15254237  3.61016949  4.06779661  4.52542373
  4.98305085  5.44067797  5.89830508  6.3559322   6.81355932  7.27118644
  7.72881356  8.18644068  8.6440678   9.10169492  9.55932203 10.01694915
 10.47457627 10.93220339 11.38983051 11.84745763 12.30508475 12.76271186
 13.22033898 13.6779661  14.13559322 14.59322034 15.05084746 15.50847458
 15.96610169 16.42372881 16.88135593 17.33898305 17.79661017 18.25423729
 18.71186441 19.16949153 19.62711864 20.08474576 20.54237288 21.        ]


In [16]:
arr, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
print(round(step, 2))

0.45


In [17]:
list1 = ['a', 'b', 'c']
list2 = [1, 2, 3]
print(list(zip(list1, list2)))

[('a', 1), ('b', 2), ('c', 3)]
