In [22]:
import numpy as np

In [23]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [24]:
arr.shape = (2, 4)
print(arr)

arr.shape = (4, 2)
print(arr)

[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [25]:
print(arr.reshape((2, 4)))
print(arr)

[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [26]:
arr = np.arange(10)
print(arr)

arr_new = arr.reshape((2, 5))
print(arr_new)

print(arr.reshape((2, 5), order='F'))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 2 4 6 8]
 [1 3 5 7 9]]


In [27]:
# Транспонирование массива
# При транспонировании одномерного массива его форма не меняется

arr = np.arange(6)
arr.shape = (2, 3)
print(arr)

print(arr.transpose())

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


In [29]:
np.iinfo(np.int16)

iinfo(min=-32768, max=32767, dtype=int16)

In [30]:
mystery = np.array([[-13586,  15203,  28445, -27117,  -1781, -17182, -18049],
       [ 25936, -30968,  -1297,  -4593,   6451,  15790,   7181],
       [ 13348,  28049,  28655,  -6012,  21762,  25397,   8225],
       [ 13240,   7994,  32592,  20149,  13754,  11795,   -564],
       [-21725,  -8681,  30305,  22260, -17918,  12578,  29943],
       [-16841, -25392, -17278,  11740,   5916,    -47, -32037]],
      dtype=np.int16)

In [46]:
elem_5_3 = mystery[4, 2]
elem_5_3

last = mystery[-1, -1]
last

line_4 = mystery[3]
print(line_4)

col_2 = mystery[:, -2]
col_2

part = mystery[1:4, 2:5]
part

rev = mystery[::-1, -1]
rev

trans = np.transpose(mystery)
trans

[13240  7994 32592 20149 13754 11795  -564]


array([[-13586,  25936,  13348,  13240, -21725, -16841],
       [ 15203, -30968,  28049,   7994,  -8681, -25392],
       [ 28445,  -1297,  28655,  32592,  30305, -17278],
       [-27117,  -4593,  -6012,  20149,  22260,  11740],
       [ -1781,   6451,  21762,  13754, -17918,   5916],
       [-17182,  15790,  25397,  11795,  12578,    -47],
       [-18049,   7181,   8225,   -564,  29943, -32037]], dtype=int16)

In [55]:
mystery = np.array([ 12279., -26024.,  28745.,  np.nan,  31244.,  -2365.,  -6974.,
        -9212., np.nan, -17722.,  16132.,  25933.,  np.nan, -16431.,
        29810.], dtype=np.float32)


In [85]:
mystery = np.array([ 12279., -26024.,  28745.,  np.nan,  31244.,  -2365.,  -6974.,
        -9212., np.nan, -17722.,  16132.,  25933.,  np.nan, -16431.,
        29810.], dtype=np.float32)

nans_index = np.isnan(mystery)
n_nan = np.sum(nans_index)

mystery[nans_index] = n_nan

mystery_new = mystery.copy()

mystery_new[nans_index] = 0

mystery.dtype = np.int32

mystery_int = mystery

array = np.sort(mystery_new)

table = array.reshape((5, 3), order='F') 

col = table[:, 1]
