In [1]:
import numpy as np

In [6]:
np.random.seed(100)
print(np.random.randint(10, size=3))
# [8 8 3]
print(np.random.randint(10, size=3))
# [7 7 0]
print(np.random.randint(10, size=3))
# [4 2 5]

print(np.random.randint(10, size=3))
print(np.random.randint(10, size=3))
print(np.random.randint(10, size=3))

[8 8 3]
[7 7 0]
[4 2 5]
[2 2 2]
[1 0 8]
[4 0 9]


In [18]:
randoms = np.random.uniform(-150, 2021, 12)
randoms

array([ 195.58477565,  789.95190737,  456.49528607, 1936.41269943,
         63.04491026,  733.58734431, -131.81473573, 1083.25593615,
       1101.81980713,  147.74019134, 1309.38650688,  160.17886231])

In [16]:
table = np.random.randint(1, 101, (3, 2), dtype=np.int8)
table

array([[ 60,  60],
       [ 25,  93],
       [100,   7]], dtype=int8)

In [21]:
even = np.arange(2, 17, step=2, dtype=np.int8)
even

mix = even
np.random.shuffle(mix)
mix

select = np.random.choice(even, size=3, replace=False)
print(select)

triplet = np.random.permutation(select)
triplet


[12  2  6]


array([ 2, 12,  6], dtype=int8)

In [23]:
np.random.seed(2022)
table1 = np.random.randint(1, 101, (3, 2))
table2 = np.random.randint(1, 101, (3, 2), dtype=np.int8)

print(table1, table2, sep='\n')


[[93 46]
 [50 56]
 [89 19]]
[[25 65]
 [44 17]
 [59 21]]
