In [1]:
import numpy as np

In [2]:
def get_loto(num):
    arr = np.random.randint(1, 101, size=(num, 5, 5))
    return arr

get_loto(3)

array([[[ 78,  49,   4,  92,  74],
        [ 16,  93,  65,  71,  85],
        [ 11,  63,  49,  33,  65],
        [ 15,  15,  56,  27,  40],
        [ 69,  83,  28,  48,  86]],

       [[ 72,  86,   6,  56,  85],
        [ 47,   3,  75,  36,  56],
        [ 99,  18,  17,  51,  33],
        [  5,  48,  34,  82,  21],
        [ 99,  37, 100,   2,  63]],

       [[ 31,  46,  39,   4,   2],
        [ 23,  20,  11,  18,  38],
        [ 59,  54,  67,  12,  30],
        [  5,   5,  26,  69,  47],
        [ 74,  29,  25,  89,  45]]])

In [19]:
def get_unique_loto(num):
    arr = np.zeros((num, 5, 5))
    
    for i in range(num):
        #print(arr[i])
        arr[i] = np.random.choice(range(1, 101), size=(5, 5), replace=False)
    return arr

get_unique_loto(2)

array([[[69., 96., 92., 79., 50.],
        [19., 22., 44., 33., 62.],
        [15., 91., 48., 65., 34.],
        [98., 43., 24., 55., 31.],
        [90., 63., 80., 20., 73.]],

       [[64., 66., 94., 16., 30.],
        [40., 99., 93., 22., 85.],
        [92., 14., 47., 29., 44.],
        [17., 48., 56.,  4., 55.],
        [71., 63., 19., 67., 72.]]])

In [36]:
def any_normal(*args):
    for i in range(len(args)):
        for k in range(i+1, len(args)):
            if np.dot(args[i], args[k]) == 0: return True
                
    return False
    

vec1 = np.array([2, 1])
vec2 = np.array([-1, 2])
vec3 = np.array([3, 4])
print(any_normal(vec1, vec2, vec3))

True


In [37]:
def min_max_dist(*args):
    min_dist = np.linalg.norm(args[0]-args[1])
    max_dist = min_dist
    
    for i in range(len(args)):
        for k in range(i+1, len(args)):
            distance = np.linalg.norm(args[i]-args[k])
            if min_dist > distance: min_dist = distance
            elif max_dist < distance: max_dist = distance
                                              
    return min_dist, max_dist
    

vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])
 
min_max_dist(vec1, vec2, vec3)

(5.196152422706632, 10.392304845413264)

In [53]:
def shuffle_seed(arr):
    seed = np.random.randint(2**32, dtype=np.int64)
    np.random.seed(seed)
    
    np.random.shuffle(arr)
    
    return arr, seed
    
print(shuffle_seed([0, 5, 1, 3, 2, 4]))

([5, 1, 0, 4, 3, 2], 2414413334)


In [120]:
def get_chess(a):  
    arr = np.zeros((a, a))
    
    arr[::2, 1::2] = 1
    arr[1::2, ::2] = 1

    return arr

get_chess(5)


array([[0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.]])